#!/usr/bin/env python3
"""
ResumeContactExtractor - Automated workflow for Resume Review and Contact Info Extraction

Generated by Workflow Observer AI
Created: 2025-08-27 20:28:27

This bot automates extracting contact information from resumes and updating Excel spreadsheets.
Applications: Microsoft Word, Microsoft Excel
Estimated time savings: 3-5 minutes per resume
"""

import logging
import json
import time
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any
import re
import traceback

# Document processing
import docx
import pandas as pd
from openpyxl import load_workbook
import pytesseract
from pdf2image import convert_from_path
import PyPDF2

# Email notifications
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class ResumeContactExtractor:
    """
    Automation bot for extracting contact information from resumes and updating Excel records
    """
    
    def __init__(self, config_file: str = "config.json"):
        """Initialize the automation bot"""
        self.config = self._load_config(config_file)
        self._setup_logging()
        self.processed_count = 0
        self.failed_count = 0
        
    def _load_config(self, config_file: str) -> Dict:
        """Load configuration from JSON file"""
        try:
            with open(config_file, 'r') as f:
                config = json.load(f)
            self._validate_config(config)
            return config
        except Exception as e:
            raise Exception(f"Failed to load config: {str(e)}")
            
    def _validate_config(self, config: Dict):
        """Validate required configuration parameters"""
        required_keys = [
            'resume_folder',
            'excel_output',
            'notification_email',
            'smtp_settings'
        ]
        for key in required_keys:
            if key not in config:
                raise ValueError(f"Missing required config key: {key}")
                
    def _setup_logging(self):
        """Setup logging configuration"""
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler('resume_extractor.log'),
                logging.StreamHandler()
            ]
        )
        self.logger = logging.getLogger(__name__)

    def extract_contact_info(self, text: str) -> Dict[str, str]:
        """
        Extract contact information from resume text using regex patterns
        """
        patterns = {
            'name': r'^([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)',
            'email': r'[\w\.-]+@[\w\.-]+\.\w+',
            'phone': r'(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}',
            'linkedin': r'linkedin\.com/in/[\w-]+'
        }
        
        contact_info = {}
        for field, pattern in patterns.items():
            match = re.search(pattern, text)
            contact_info[field] = match.group(0) if match else ''
            
        return contact_info

    def process_document(self, file_path: str) -> Dict[str, str]:
        """Process resume document and extract contact information"""
        try:
            text = ""
            if file_path.endswith('.docx'):
                doc = docx.Document(file_path)
                text = '\n'.join([paragraph.text for paragraph in doc.paragraphs])
            elif file_path.endswith('.pdf'):
                pdf_reader = PyPDF2.PdfReader(file_path)
                text = '\n'.join([page.extract_text() for page in pdf_reader.pages])
            else:
                raise ValueError(f"Unsupported file format: {file_path}")
                
            contact_info = self.extract_contact_info(text)
            return contact_info
            
        except Exception as e:
            self.logger.error(f"Failed to process document {file_path}: {str(e)}")
            raise

    def update_excel(self, contact_info: Dict[str, str]):
        """Update Excel spreadsheet with contact information"""
        try:
            df = pd.read_excel(self.config['excel_output'])
            new_row = pd.DataFrame([contact_info])
            df = pd.concat([df, new_row], ignore_index=True)
            df.to_excel(self.config['excel_output'], index=False)
            
        except Exception as e:
            self.logger.error(f"Failed to update Excel: {str(e)}")
            raise

    def send_notification(self, success: bool, message: str):
        """Send email notification about processing results"""
        try:
            smtp_config = self.config['smtp_settings']
            
            msg = MIMEMultipart()
            msg['From'] = smtp_config['username']
            msg['To'] = self.config['notification_email']
            msg['Subject'] = 'Resume Processing Report'
            
            body = f"""
            Resume Processing Complete
            
            Status: {'Success' if success else 'Failed'}
            Message: {message}
            
            Processed: {self.processed_count}
            Failed: {self.failed_count}
            """
            
            msg.attach(MIMEText(body, 'plain'))
            
            with smtplib.SMTP(smtp_config['server'], smtp_config['port']) as server:
                server.starttls()
                server.login(smtp_config['username'], smtp_config['password'])
                server.send_message(msg)
                
        except Exception as e:
            self.logger.error(f"Failed to send notification: {str(e)}")

    def run_automation(self) -> Dict[str, Any]:
        """
        Main automation workflow
        
        Returns:
            Dict with execution results
        """
        start_time = time.time()
        results = {
            'processed_files': 0,
            'failed_files': 0,
            'execution_time': 0
        }
        
        try:
            resume_folder = Path(self.config['resume_folder'])
            resume_files = list(resume_folder.glob('*.docx')) + list(resume_folder.glob('*.pdf'))
            
            for resume_file in resume_files:
                try:
                    self.logger.info(f"Processing {resume_file}")
                    contact_info = self.process_document(str(resume_file))
                    self.update_excel(contact_info)
                    self.processed_count += 1
                    self.logger.info(f"Successfully processed {resume_file}")
                    
                except Exception as e:
                    self.failed_count += 1
                    self.logger.error(f"Failed to process {resume_file}: {str(e)}")
                    continue
            
            execution_time = time.time() - start_time
            results['processed_files'] = self.processed_count
            results['failed_files'] = self.failed_count
            results['execution_time'] = execution_time
            
            success = self.failed_count == 0
            self.send_notification(
                success,
                f"Processed {self.processed_count} resumes in {execution_time:.2f} seconds"
            )
            
            return results
            
        except Exception as e:
            self.logger.error(f"Automation failed: {str(e)}")
            self.send_notification(False, f"Automation failed: {str(e)}")
            raise

def main():
    """Main execution function"""
    bot = ResumeContactExtractor()
    try:
        result = bot.run_automation()
        print(f"✅ Automation completed: {result}")
    except Exception as e:
        print(f"❌ Automation failed: {traceback.format_exc()}")

if __name__ == "__main__":
    main()